name: Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: docker

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        server_url: https://forgejo.home.potato

    - name: Deploy
      run: make deploy
